package nz.ac.vuw.yamf.reporting;

import java.util.function.Predicate;

/**
 * Utility to reduce the stackframe reported by removing frames generated by the junit framework.
 * @author jens diietriich
 */
public class StackTraceFilters {

    public static Predicate<StackTraceElement> ALL = stackTraceElement -> true;

    public static Predicate<StackTraceElement> REMOVE_JUNIT_ENGINE = stackTraceElement ->
            !(stackTraceElement.getClassName().startsWith("org.junit.platform") || stackTraceElement.getClassName().startsWith("org.junit.jupiter.engine")
        );

    public static Predicate<StackTraceElement> REMOVE_JDK_INTERNAL = stackTraceElement -> !(stackTraceElement.getClassName().startsWith("jdk.internal"));

    public static Predicate<StackTraceElement> DEFAULT = stackTraceElement ->
            !(stackTraceElement.getClassName().startsWith("jdk.internal") ||
            stackTraceElement.getClassName().startsWith("org.junit.jupiter.engine") ||
            stackTraceElement.getClassName().startsWith("org.junit.platform")
        );

}
